/* bl_sign_pubkey_local.template.h -- FORMAT TEMPLATE for the ECDSA P-256 public key header
 *
 * This template is documentation only; it is NEVER included by any build and is safe
 * to commit. The real bl_sign_pubkey_local.h is generated by:
 *
 *   uv run --python 3.12 --with cryptography tools/sign_image.py --keygen \
 *       --chip-dir port/stm32f4/f411ceu6
 *
 * which writes the header into the chip port directory (gitignored via
 * .gitignore, ADR-020: NO key material may ever enter git, including test keys)
 * plus the matching private key sign_test_key.pem (keep local, rotate before
 * production).
 *
 * Field semantics:
 *   BL_SIGN_PUBKEY_BYTES -- P-256 public key Qx||Qy, 32+32 = 64 bytes, BIG-ENDIAN
 *   raw order (uECC default uECC_VLI_NATIVE_LITTLE_ENDIAN=0 uses standard big-endian
 *   for keys/signatures, matching cryptography/openssl output directly).
 *
 * NOTE: comments in this header MUST stay pure ASCII. armcc reads source files in
 * the local ANSI codepage (GBK on this machine); some UTF-8 multibyte sequences
 * swallow the following newline inside comments and break compilation
 * ("expected a declaration", observed 2026-09-30).
 */

#ifndef BL_SIGN_PUBKEY_LOCAL_H
#define BL_SIGN_PUBKEY_LOCAL_H

/* Placeholder values below only illustrate the format; using them as-is makes
 * every signature verification fail. Replace with real key bytes. */
#define BL_SIGN_PUBKEY_BYTES  \
    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, \
    0x08, 0x09, 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, \
    0x10, 0x11, 0x12, 0x13, 0x14, 0x15, 0x16, 0x17, \
    0x18, 0x19, 0x1A, 0x1B, 0x1C, 0x1D, 0x1E, 0x1F, \
    0x20, 0x21, 0x22, 0x23, 0x24, 0x25, 0x26, 0x27, \
    0x28, 0x29, 0x2A, 0x2B, 0x2C, 0x2D, 0x2E, 0x2F, \
    0x30, 0x31, 0x32, 0x33, 0x34, 0x35, 0x36, 0x37, \
    0x38, 0x39, 0x3A, 0x3B, 0x3C, 0x3D, 0x3E, 0x3F
/* End of placeholder values. Replace before production use. */

#endif /* BL_SIGN_PUBKEY_LOCAL_H */
