#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""sign_image.py — 镜像签名辅助工具（ADR-020，HIL/开发用；正式签名集成后续进 LBU）

功能：
  --keygen  生成 P-256 测试密钥对：私钥 PEM（本地保管，不入库）+
            公钥头 bl_sign_pubkey_local.h（写入目标芯片端口目录，该文件已被 .gitignore）
  --sign    计算镜像 SHA-256/CRC32 → ECDSA P-256 签名 → 组装 0x11 VERIFY_SIGNED 帧
            （protocol.md §5.11：DATA = size(4,LE) + crc32(4,LE) + signature(64B)）

签名口径：对**填充后镜像**（4 字节 0xFF 对齐，与上位机升级口径一致）的 SHA-256 摘要
签名；signature = r‖s 各 32 字节定宽大端裸序（与固件 uECC 默认大端字节序直通）。

用法（依赖隔离运行，勿装全局）：
  uv run --python 3.12 --with cryptography tools/sign_image.py --keygen --chip-dir port/stm32f4/f411ceu6
  uv run --python 3.12 --with cryptography tools/sign_image.py --sign app.bin [--key sign_test_key.pem]

退出码：0 成功 / 1 失败 / 2 参数错误。
私钥与公钥头均不入库（ADR-020，用户要求：任何形态的密钥不进 git）。
"""
import argparse
import struct
import sys
import zlib
from pathlib import Path

SOF = b"\xAA\x55"
EOF = b"\x55\xAA"
VER = 0x01
CMD_VERIFY_SIGNED = 0x11

try:
    from cryptography.exceptions import InvalidSignature
    from cryptography.hazmat.primitives import hashes, serialization
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import decode_dss_signature
except ImportError:
    print("[X] 缺少 cryptography：请用 uv run --with cryptography ... 运行", file=sys.stderr)
    sys.exit(2)


def crc16_modbus(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b
        for _ in range(8):
            crc = (crc >> 1) ^ 0xA001 if (crc & 1) else (crc >> 1)
    return crc


def build_verify_signed_frame(seq: int, app_size: int, app_crc32: int, sig: bytes) -> bytes:
    data = struct.pack("<II", app_size, app_crc32) + sig
    head = bytes([VER, CMD_VERIFY_SIGNED, seq, len(data) & 0xFF, (len(data) >> 8) & 0xFF])
    c = crc16_modbus(head + data)
    return SOF + head + data + bytes([c & 0xFF, (c >> 8) & 0xFF]) + EOF


def pub_header_text(qx: bytes, qy: bytes) -> str:
    raw = qx + qy
    lines = []
    for i in range(0, 64, 8):
        chunk = ", ".join(f"0x{b:02X}" for b in raw[i:i + 8])
        last = (i == 56)
        # 多行宏：除末行外每行行尾都要续行反斜杠
        lines.append("    " + chunk + ("" if last else ", \\"))
    joined = "\n".join(lines)
    # 注释刻意全 ASCII：armcc 以本地编码（GBK）读源文件，UTF-8 中文注释的
    # 个别字节序列会吞掉换行导致 "expected a declaration"（2026-09-30 实测）
    return (
        "/* bl_sign_pubkey_local.h -- generated by tools/sign_image.py --keygen\n"
        " * P-256 public key, Qx||Qy big-endian raw, 64 bytes total (ADR-020).\n"
        " * LOCAL ONLY: kept out of git via .gitignore. Keep the matching\n"
        " * private key (sign_test_key.pem) safe; rotate before production. */\n\n"
        "#ifndef BL_SIGN_PUBKEY_LOCAL_H\n"
        "#define BL_SIGN_PUBKEY_LOCAL_H\n\n"
        "#define BL_SIGN_PUBKEY_BYTES \\\n" + joined + "\n\n"
        "#endif /* BL_SIGN_PUBKEY_LOCAL_H */\n"
    )


def do_keygen(chip_dir: Path, key_out: Path) -> int:
    chip_dir.mkdir(parents=True, exist_ok=True)
    key = ec.generate_private_key(ec.SECP256R1())
    pn = key.public_key().public_numbers()
    qx = pn.x.to_bytes(32, "big")
    qy = pn.y.to_bytes(32, "big")

    header = chip_dir / "bl_sign_pubkey_local.h"
    header.write_text(pub_header_text(qx, qy), encoding="utf-8", newline="\n")
    pem = key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )
    key_out.write_bytes(pem)

    print(f"[OK] 公钥头：{header}")
    print(f"[OK] 私钥  ：{key_out}（本地妥善保管，勿提交/勿外发；量产前换正式密钥）")
    print(f"[OK] 公钥 Qx={qx.hex().upper()}")
    print(f"[OK] 公钥 Qy={qy.hex().upper()}")
    print("[提示] 固件侧启用：board_config.h 置 BL_SIGN_EN=1 后全量重建（编译日志应出现签名警告行）")
    return 0


def do_sign(image: Path, key_path: Path) -> int:
    img = image.read_bytes()
    if len(img) % 4:
        img += b"\xFF" * (4 - len(img) % 4)   # 与上位机升级同口径：4 字节 0xFF 填充
    app_size = len(img)
    app_crc32 = zlib.crc32(img) & 0xFFFFFFFF
    digest = hashes.Hash(hashes.SHA256())
    digest.update(img)
    sha = digest.finalize()

    key = serialization.load_pem_private_key(key_path.read_bytes(), password=None)
    if not isinstance(key, ec.EllipticCurvePrivateKey) or not isinstance(
            key.curve, ec.SECP256R1):
        print("[X] 私钥不是 EC P-256 密钥", file=sys.stderr)
        return 1
    # 对镜像字节签名（库内做 SHA-256）≡ 对 SHA-256 镜像摘要签名（protocol.md §5.11）
    der = key.sign(img, ec.ECDSA(hashes.SHA256()))
    r, s = decode_dss_signature(der)
    sig = r.to_bytes(32, "big") + s.to_bytes(32, "big")   # 定宽大端裸序（§5.11）

    frame = build_verify_signed_frame(seq=0x01, app_size=app_size,
                                      app_crc32=app_crc32, sig=sig)
    print(f"镜像          ：{image}（填充后 {app_size} B）")
    print(f"app_crc32     ：0x{app_crc32:08X}")
    print(f"app_sha256    ：{sha.hex().upper()}")
    print(f"signature(64B)：{sig.hex().upper()}")
    print(f"VERIFY_SIGNED 帧（{len(frame)}B，SEQ=0x01，可经 LBU raw / VOFA+ 发送）：")
    print(f"  {frame.hex().upper()}")
    print("[提示] 固件须为 BL_SIGN_EN=1 构建且公钥与本私钥配对；篡改镜像任意字节后验签应回 SIGN_ERROR")
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="镜像签名辅助（ADR-020，HIL/开发用）")
    ap.add_argument("--keygen", action="store_true",
                    help="生成 P-256 测试密钥对（私钥 PEM + 公钥本地头）")
    ap.add_argument("--sign", metavar="IMAGE", help="对待升级镜像签名并输出 0x11 帧")
    ap.add_argument("--chip-dir", default="port/stm32f4/f411ceu6",
                    help="公钥头输出目录（默认 f411 端口目录）")
    ap.add_argument("--key", default="sign_test_key.pem", help="私钥 PEM 路径")
    a = ap.parse_args()

    if a.keygen and a.sign:
        print("[X] --keygen 与 --sign 互斥", file=sys.stderr)
        return 2
    if a.keygen:
        return do_keygen(Path(a.chip_dir), Path(a.key))
    if a.sign:
        return do_sign(Path(a.sign), Path(a.key))
    ap.print_help()
    return 2


if __name__ == "__main__":
    try:
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    except Exception:
        pass
    sys.exit(main())
